# A Dockerfile to build an OpenShift Jenkins Slave Agent.
# It's based on the OpenShift Maven image,
# which includes OpenJDK 1.8 and Maven 3.x.

# The v3.10 digest...
FROM openshift/jenkins-slave-maven-centos7@sha256:7575a0adc03ab029b84d1a9743ba9979875ba06c5207dfa7f791fec039159599
MAINTAINER Alan Christie (alanbchristie)

ENV INSTALL_PATH /project-atomic

ENV BUILDAH_VERSION 1.0
ENV BUILDAH_SUB_PATH src/github.com/projectatomic/buildah

ENV PODMAN_VERSION 0.5.1
ENV PODMAN_SUB_PATH src/github.com/projectatomic/libpod

ENV SKOPEO_VERSION 0.1.29
ENV SKOPEO_SUB_PATH src/github.com/projectatomic/skopeo

ENV GOPATH ${INSTALL_PATH}

USER root

# Install gcc (required to build buildah)
RUN yum -y group install "Development Tools"

# Install packages required by buildah & podman
RUN yum -y install \
    atomic-registries \
    bats \
    btrfs-progs-devel \
    bzip2 \
    conmon \
    containernetworking-cni \
    device-mapper-devel \
    git \
    glibc-devel \
    glibc-static \
    glib2-devel \
    go \
    go-md2man \
    golang \
    golang-github-cpuguy83-go-md2man \
    gpgme-devel \
    iptables \
    libassuan-devel \
    libgpg-error-devel \
    libseccomp-devel \
    libselinux-devel \
    make \
    ostree-devel \
    pkgconfig \
    runc \
    skopeo-containers

# Get, make and install buildah
WORKDIR ${INSTALL_PATH}
RUN git clone https://github.com/projectatomic/buildah ./${BUILDAH_SUB_PATH}
WORKDIR ${BUILDAH_SUB_PATH}
RUN git checkout tags/V${BUILDAH_VERSION}
RUN make; make install

# Get, make and install podman
WORKDIR ${INSTALL_PATH}
RUN git clone https://github.com/projectatomic/libpod ./${PODMAN_SUB_PATH}
WORKDIR ${PODMAN_SUB_PATH}
RUN git checkout tags/v${PODMAN_VERSION} 2> /dev/null
RUN make install.tools; make BUILDTAGS='seccomp selinux apparmor'; make install

# Get, make and install skopeo
WORKDIR ${INSTALL_PATH}
RUN git clone https://github.com/projectatomic/skopeo ./${SKOPEO_SUB_PATH}
WORKDIR ${SKOPEO_SUB_PATH}
RUN git checkout tags/v${SKOPEO_VERSION} 2> /dev/null
RUN make binary-local; make install

# Some handy labels...
LABEL buildah.version=${BUILDAH_VERSION}
LABEL podman.version=${PODMAN_VERSION}
LABEL scopeo.version=${SKOPEO_VERSION}
LABEL name="Jenkins Buildah Slave Agent"
LABEL author="Alan Christie (alanbchristie)"

# Buildah needs to run as root.
# We're root at this stage of the script, so leave the USER alone.
# Do not return to the underlying user id (1001).
WORKDIR ${HOME}
